float32 score # score / confidence value from detector
uint8 label # label index: {"person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat", "trafficlight", "firehydrant", "stopsign", "bird", "animal", "chair", "couch", "bed", "diningtable", "toilet", "tv", "microwave", "oven", "toaster", "sink", "refrigerator"};
BoundingBox bbox # bounding box in pixel coordinates in original image
